/**
 * Aera Work Context window — WO-AGC-002 Remit C (desktop retarget).
 *
 * Isolated native auxiliary window presenting one shared WorkContext. Follows
 * the established ProfileCreateWindow pattern exactly: a sandboxed
 * BrowserWindow loads the vite-built native-ui document; the page requests
 * actions ONLY by navigating to a private URL scheme (intercepted here), and
 * receives serialised view models ONLY via CustomEvent dispatch. The renderer
 * gets no node integration, no store paths and no write capability (§14).
 *
 * All durable operations run in the main process through
 * `CollabWorkspaceService` → the established substrate owners.
 */

// Namespace import: see the note in `electron-reveal.ts`.
import * as electron from 'electron'
import type { BrowserWindow } from 'electron'
import { fileURLToPath } from 'node:url'
import {
  auxiliaryWindowChromeOptions,
  auxiliaryWindowHasCustomFrame,
} from './auxiliary-window-options.ts'
import { revealApplication } from './electron-reveal.ts'
import {
  CollabHonestError,
  type CollabWorkspaceService,
} from './aera-collab-service.ts'
import type { CollabHostSeam } from './aera-collab-seam.ts'

const WORK_CONTEXT_SCHEME = 'aera-work-context:'
const MAX_ACTION_QUERY_BYTES = 8192
const WORK_CONTEXT_DOCUMENT = fileURLToPath(new URL('./native-ui/work-context.html', import.meta.url))

/** Actions the page may request. Anything else is ignored. */
export type WorkContextAction =
  | { readonly action: 'open', readonly workOrderId: string }
  | { readonly action: 'refresh' }
  | { readonly action: 'note', readonly text: string }
  | { readonly action: 'evidence', readonly nodeId: string, readonly summary: string }
  | { readonly action: 'open-source', readonly path: string }
  | { readonly action: 'close-context' }

/** Parse only the actions generated by the local work-context document. */
export function parseWorkContextAction(href: string): WorkContextAction | undefined {
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== WORK_CONTEXT_SCHEME
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== '') return undefined
  if (Buffer.byteLength(url.search, 'utf8') > MAX_ACTION_QUERY_BYTES) return undefined
  const keys = [...url.searchParams.keys()].sort()
  const action = url.hostname
  const one = (key: string): string | undefined => {
    const value = url.searchParams.get(key)
    return value === null ? undefined : value
  }
  switch (action) {
    case 'refresh':
    case 'close-context':
      return keys.length === 0 ? { action } : undefined
    case 'open': {
      if (keys.join(',') !== 'workOrderId') return undefined
      const workOrderId = one('workOrderId')
      return workOrderId === undefined || workOrderId.trim() === '' ? undefined : { action, workOrderId: workOrderId.trim() }
    }
    case 'note': {
      if (keys.join(',') !== 'text') return undefined
      const text = one('text')
      return text === undefined ? undefined : { action, text }
    }
    case 'evidence': {
      if (keys.join(',') !== 'nodeId,summary' && keys.join(',') !== 'nodeId') return undefined
      const nodeId = one('nodeId')
      if (nodeId === undefined || nodeId.trim() === '') return undefined
      return { action, nodeId: nodeId.trim(), summary: one('summary') ?? '' }
    }
    case 'open-source': {
      if (keys.join(',') !== 'path') return undefined
      const path = one('path')
      return path === undefined || path.trim() === '' ? undefined : { action, path }
    }
    default:
      return undefined
  }
}

export interface WorkContextWindowOptions {
  readonly service: CollabWorkspaceService
  readonly seam: CollabHostSeam
}

/** Own one isolated Work Context window; repeated opens focus the same instance. */
export class WorkContextWindow {
  private window: BrowserWindow | undefined
  private busy = false
  private disposed = false

  constructor(private readonly options: WorkContextWindowOptions) {}

  open(): void {
    const existing = this.window
    if (existing !== undefined && !existing.isDestroyed()) {
      revealApplication(existing)
      return
    }
    this.disposed = false
    this.busy = false
    const window = new electron.BrowserWindow({
      title: 'Aera Work Context',
      ...auxiliaryWindowChromeOptions(),
      width: 900,
      height: 720,
      minWidth: 640,
      minHeight: 480,
      show: false,
      autoHideMenuBar: true,
      backgroundColor: '#202124',
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
        nodeIntegrationInSubFrames: false,
        sandbox: true,
        webSecurity: true,
        webviewTag: false,
        spellcheck: false,
      },
    })
    this.window = window
    window.accessibleTitle = 'Aera Work Context'
    window.removeMenu()
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
    const navigate = (event: Electron.Event, href: string): void => {
      const action = parseWorkContextAction(href)
      if (action === undefined) {
        if (href.startsWith(WORK_CONTEXT_SCHEME)) event.preventDefault()
        else if (!href.startsWith('file:')) event.preventDefault()
        return
      }
      event.preventDefault()
      void this.handleAction(action)
    }
    window.webContents.on('will-navigate', navigate)
    window.webContents.on('will-redirect', navigate)
    window.once('ready-to-show', () => {
      if (!this.disposed && this.window === window && !window.isDestroyed()) revealApplication(window)
    })
    window.webContents.once('did-finish-load', () => {
      void this.pushState()
    })
    window.on('closed', () => {
      if (this.window === window) this.window = undefined
      // §5G honesty: closing the window ends the participation session
      // through the canonical owner; durable records survive.
      void this.options.service.closeWorkContext().catch(() => {})
    })
    void window.loadFile(WORK_CONTEXT_DOCUMENT, {
      query: {
        platform: process.platform,
        frame: String(auxiliaryWindowHasCustomFrame()),
      },
    }).catch(() => {
      if (!this.disposed && this.window === window) window.close()
    })
  }

  close(): void {
    this.disposed = true
    const window = this.window
    this.window = undefined
    if (window !== undefined && !window.isDestroyed()) window.close()
  }

  private async dispatch(detail: unknown): Promise<void> {
    const window = this.window
    if (window === undefined || window.isDestroyed()) return
    const payload = JSON.stringify(detail)
    await window.webContents.executeJavaScript(
      `window.dispatchEvent(new CustomEvent('aera-work-context-state', { detail: ${payload} }))`,
      true,
    ).catch(() => {})
  }

  /** Push availability + (when joined) the current context view to the page. */
  private async pushState(notice?: string): Promise<void> {
    const service = this.options.service
    const availability = service.availability()
    if (!service.isJoined()) {
      await this.dispatch({
        kind: 'idle',
        availability,
        ...(notice === undefined ? {} : { notice }),
      })
      return
    }
    try {
      const view = await service.contextView()
      await this.dispatch({
        kind: 'context',
        availability,
        view,
        ...(notice === undefined ? {} : { notice }),
      })
    } catch (cause) {
      await this.pushError(cause)
    }
  }

  private async pushError(cause: unknown): Promise<void> {
    const detail = cause instanceof CollabHonestError
      ? { kind: 'error', code: cause.code, reason: cause.message }
      : { kind: 'error', code: 'UNEXPECTED', reason: cause instanceof Error ? cause.message : String(cause) }
    await this.dispatch(detail)
  }

  private async handleAction(action: WorkContextAction): Promise<void> {
    if (this.busy || this.disposed) return
    this.busy = true
    try {
      const service = this.options.service
      switch (action.action) {
        case 'open': {
          await this.dispatch({ kind: 'busy', message: `Opening ${action.workOrderId}…` })
          await service.openWorkContext(action.workOrderId)
          await this.pushState(`Opened ${action.workOrderId}`)
          break
        }
        case 'refresh': {
          await this.pushState()
          break
        }
        case 'note': {
          const result = await service.recordProgressNote(action.text)
          await this.pushState(
            `Progress note recorded (${result.eventId}${result.attributed ? '' : '; recorded as UNATTRIBUTED_CHANGE'})`,
          )
          break
        }
        case 'evidence': {
          const result = await service.attachEvidenceReference(action.nodeId, action.summary)
          await this.pushState(`Evidence reference recorded (${result.eventId})`)
          break
        }
        case 'open-source': {
          const local = service.resolveSourcePathToLocal(action.path)
          await this.options.seam.openLocalSource(local)
          await this.pushState(`Opened source ${action.path}`)
          break
        }
        case 'close-context': {
          await service.closeWorkContext()
          await this.pushState('Context closed. Durable records survive; reopen by WorkOrderId.')
          break
        }
      }
    } catch (cause) {
      await this.pushError(cause)
    } finally {
      this.busy = false
    }
  }
}
